"""
train.py

Execute the fine-tuning of GPT-2 on the already tokenized MTG card dataset.

Prerequisites:

- The .pt files generated by tokenize_dataset.py:
      tokenized_train.pt
      tokenized_val.pt

- The libraries:
      pip install transformers torch
"""

from pathlib import Path

import torch
from torch.utils.data import Dataset
from transformers import (
    GPT2LMHeadModel,
    GPT2TokenizerFast,
    Trainer,
    TrainingArguments,
)


class MTGDataset(Dataset):
    """
    Python class that "wraps" the tokenized tensors saved in the .pt files

    Each example is a single tokenized card (input_ids + attention_mask)

    labels = input_ids because the model must learn to predict the next token in an autoregressive sequence
    """

    def __init__(self, data: dict):
        # save the tensors of the cards already tokenized by 'tokenize_dataset.py'
        self.input_ids = data["input_ids"]
        self.attention_mask = data["attention_mask"]

    def __len__(self):
        # total number of cards in the dataset
        return self.input_ids.size(0)

    def __getitem__(self, idx):
        """
        Returns a single example (a card):
        - input_ids: sequence of tokens of the card
        - attention_mask: indicates which tokens are real (1) and which are padding (0)
        - labels: for autoregressive GPT-2, they are the same as input_ids
        """
        return {
            "input_ids": self.input_ids[idx],
            "attention_mask": self.attention_mask[idx],
            "labels": self.input_ids[idx], # the model must learn to predict the sequence itself => labels = input_ids
        }


def load_tokenizer_with_special_tokens(model_name: str) -> GPT2TokenizerFast:
    """
    Load the GPT-2 tokenizer and add the special tokens <|startofcard|> and <|endofcard|> as done in 'tokenize_dataset.py'.

    The model must use the same tokenizer used to preprocess the data.
    """
    tokenizer = GPT2TokenizerFast.from_pretrained(model_name)

    # GPT-2 does not have a pad token so use eos as pad
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # add the two tokens that delimit the cards
    special_tokens_dict = {
        "additional_special_tokens": ["<|startofcard|>", "<|endofcard|>"]
    }
    tokenizer.add_special_tokens(special_tokens_dict)

    return tokenizer


def main():
    # model name
    MODEL_NAME = "gpt2"

    # tokenized dataset paths
    TRAIN_PATH = "../../data/processed_datasets/tokenized_datasets/tokenized_train.pt"
    VAL_PATH = "../../data/processed_datasets/tokenized_datasets/tokenized_val.pt"

    # path to save the fine-tuned model
    OUTPUT_DIR = "../../models/gpt2-mtg"

    # training parameters
    NUM_TRAIN_EPOCHS = 3.0 # number of full passes the model makes over the entire training dataset
    PER_DEVICE_TRAIN_BATCH_SIZE = 4 # number of sequences processed together by each GPU/CPU during training
    PER_DEVICE_EVAL_BATCH_SIZE = 4 # number of sequences processed together by each GPU/CPU during evaluation
    LEARNING_RATE = 5e-5 # controls how much the model updates its weights at each step
    WARMUP_STEPS = 500 # initial phase where LR gradually increases
    WEIGHT_DECAY = 0.01 # regularization  
    LOGGING_STEPS = 100 # each 100 steps log training metrics
    SAVE_STEPS = 1000 # each 1000 steps save a checkpoint
    SAVE_TOTAL_LIMIT = 2  # keep only the last 2 checkpoints

    # convert paths to Path objects
    train_path = Path(TRAIN_PATH)
    val_path = Path(VAL_PATH)
    output_dir = Path(OUTPUT_DIR)
    # create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # load the tokenizer and add special tokens
    print(f"Loading tokenizer for model '{MODEL_NAME}'...")
    tokenizer = load_tokenizer_with_special_tokens(MODEL_NAME)

    # updated vocabulary size with the 2 added tokens
    vocab_size = len(tokenizer)
    print(f"Vocabulary size with special tokens: {vocab_size}")

    # load the pre-trained GPT-2 model
    print(f"Loading pre-trained model '{MODEL_NAME}'...")
    model = GPT2LMHeadModel.from_pretrained(MODEL_NAME)

    # set the pad token 
    model.config.pad_token_id = tokenizer.pad_token_id

    # update model embeddings to include new tokens
    model.resize_token_embeddings(vocab_size)

    # load the tokenized data (.pt)
    print(f"Loading training data from {train_path} ...")
    train_data = torch.load(train_path)
    print(f"  -> input_ids shape train: {train_data['input_ids'].shape}")

    print(f"Loading validation data from {val_path} ...")
    val_data = torch.load(val_path)
    print(f"  -> input_ids shape val:   {val_data['input_ids'].shape}")

    # create PyTorch datasets from tensors
    train_dataset = MTGDataset(train_data)
    val_dataset = MTGDataset(val_data)

    # define training parameters (TrainingArguments)
    training_args = TrainingArguments(
        output_dir=str(output_dir),
        overwrite_output_dir=True, # overwrite output directory if it exists
        num_train_epochs=NUM_TRAIN_EPOCHS,       
        per_device_train_batch_size=PER_DEVICE_TRAIN_BATCH_SIZE,
        per_device_eval_batch_size=PER_DEVICE_EVAL_BATCH_SIZE,
        learning_rate=LEARNING_RATE,
        warmup_steps=WARMUP_STEPS,               
        weight_decay=WEIGHT_DECAY,            
        logging_steps=LOGGING_STEPS,             
        save_steps=SAVE_STEPS,                   
        save_total_limit=SAVE_TOTAL_LIMIT,      
    )

    # create the Trainer (object that manages training, evaluation, logging, saving)
    trainer = Trainer(
        model=model, # the model to fine-tune
        args=training_args, # settings of the training
        train_dataset=train_dataset, # training dataset
        eval_dataset=val_dataset, # evaluation dataset
        tokenizer=tokenizer, # to save tokenizer along with the model
    )

    # start training
    print("Starting training...")
    trainer.train()
    print("Training completed.")

    # final evaluation on validation set
    print("Final evaluation on validation set...")
    metrics = trainer.evaluate()
    print(metrics)

    # save the fine-tuned model and tokenizer
    print(f"Saving model and tokenizer to {output_dir} ...")
    trainer.save_model(output_dir) # save the weights of the model + config
    tokenizer.save_pretrained(output_dir) # save the tokenizer
    print("Saving completed.")


if __name__ == "__main__":
    main()
